symbol="ETH"
k = 0.4
expected_rate_p = 2.0
partial_sell_rate_p = 100 # 익절시 매도비율 %
emergency_sell_rate_p = 2.5
# candle_interval="minute60"
candle_interval="minute240"
# candle_interval="minute10"
# candle_interval="minute5"
# candle_interval="minute1"
# candle_interval="day"
