symbol: "ETH"
k: 0.5
max_buy_limit_p: 3.0 # 직전 candle 이 너무 커서 buy price 가 너무 높은 것을 방지하기 위한 상한선
expected_k: 0.6 # 익절 기준 (k기준)
expected_rate_p: 2.0 # 익절 기준 (%기준)
partial_sell_rate_p: 100 # 익절시 매도비율 %
emergency_sell_rate_p: 2.0
candle_interval: "day"
partial_sell_delay_sec: 300
